# name: CI Pipeline

# on:
#   pull_request:
#   push:
#     branches: [main]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test




name: Tests

on:
  push:
    branches:
      - develop
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: |
          echo "Running tests for $GITHUB_REF_NAME"

          # Fail only for EXP-2 branch
          if [[ "$GITHUB_REF_NAME" == "feature/EXP-2-checkout-freeze" ]]; then
            echo "Checkout tests failed"
            exit 1
          fi

          echo "All tests passed"
